const express = require('express');
const app = express();

const truthQuestions = [
  "What is your biggest fear?",
  "Have you ever lied to your best friend?",
  "What is the most embarrassing thing you've ever done?",
  "What's a secret you've never told anyone?",
  "What's something you're glad your family doesn't know about you?",
  "Have you ever cheated on a test?",
  "Who was your first crush?",
  "What's something you regret doing?",
  "Have you ever stolen anything?",
  "What's the weirdest dream you've ever had?",
  "What's your biggest insecurity?",
  "What's the worst thing you've ever said to someone?",
  "Have you ever pretended to be sick to skip something?",
  "What's the most childish thing you still do?",
  "Have you ever broken the law?",
  "What's the strangest thing you've ever eaten?",
  "Have you ever had a crush on a teacher?",
  "What's one thing you wish people knew about you?",
  "Have you ever snooped through someone's phone?",
  "What's the biggest lie you've ever told without getting caught?",
  "Have you ever cried in public?",
  "What's your guilty pleasure?",
  "Have you ever spread a rumor?",
  "What was your worst date ever like?",
  "What's something you're too embarrassed to admit?",
  "Have you ever stalked someone on social media?",
  "What's the most trouble you've ever gotten into at school?",
  "Have you ever bullied someone or been bullied?",
  "What's a habit you have that irritates others?",
  "What's the longest you've gone without showering?",
  "Have you ever cheated on a partner?",
  "What's the most expensive thing you've ever stolen?",
  "What's a secret talent you have?",
  "Have you ever lied about your age?",
  "What's the most childish thing you do when you're stressed?",
  "Have you ever faked being sick to get out of something?",
  "What's the weirdest nickname you've ever had?",
  "Have you ever pretended to like a gift you hated?",
  "What's the worst haircut you've ever had?",
  "Have you ever been caught doing something you shouldn't?",
  "What's one thing you wish you could change about yourself?",
  "Have you ever broken someone's heart?",
  "What's the most embarrassing text message you've sent?",
  "Have you ever been caught sneaking out?",
  "What's the craziest thing you've done on a dare?",
  "Have you ever lied on a job application?",
  "What's a fear you have that might seem silly to others?",
  "Have you ever been in love with someone who didn't love you back?",
  "What's the most ridiculous thing you've done for love?",
  "Have you ever stolen money from someone?",
  "What's something you've never told your parents?",
  "Have you ever been blackout drunk?",
  "What's the worst mistake you've made in a relationship?",
  "Have you ever ghosted someone?",
  "What's the biggest age gap you've had with a partner?",
  "Have you ever sent a text you instantly regretted?",
  "What's a secret you've kept from your closest friend?",
  "Have you ever lied to get out of trouble?",
  "What's the most outrageous story you've made up?",
  "Have you ever peeped into someone's diary or journal?",
  "What's one embarrassing thing that happened to you recently?",
  "Have you ever cried yourself to sleep?",
  "What's the worst thing you've done to a sibling?",
  "Have you ever cheated in a game or sport?",
  "What's something you've been dishonest about to protect someone's feelings?",
  "Have you ever broken a bone or had a serious injury?",
  "What's the most awkward thing that happened on a date?",
  "Have you ever lied about being busy to avoid someone?",
  "What's a weird or gross habit you have?",
  "Have you ever had a crush on a friend's partner?",
  "What's the worst excuse you've used to get out of something?",
  "Have you ever been fired from a job?",
  "What's the worst gift you've ever received?",
  "Have you ever flirted with someone just to make someone else jealous?",
  "What's the most immature thing you've done in the past month?",
  "Have you ever pretended to know something when you didn't?",
  "What's the most embarrassing thing you've done for attention?",
  "Have you ever lied in a relationship to avoid hurting someone?",
  "What's the most impulsive thing you've ever done?",
  "Have you ever had a crush on a fictional character?",
  "What's the weirdest thing you've Googled?",
  "Have you ever accidentally sent a message to the wrong person?",
  "What's something you've done that you hope no one finds out about?",
  "Have you ever been caught lying?",
  "What's the most embarrassing thing you've done while drunk?",
  "Have you ever snooped through someone's personal belongings?",
  "What's a secret you've never told your best friend?",
  "Have you ever sabotaged your own chances at something?",
  "What's the worst trouble you've been in because of peer pressure?",
  "Have you ever broken a promise to someone important?",
  "What's the most childish thing you do when you're angry?",
  "Have you ever been in a physical fight?",
  "What's one thing you wish you could erase from your past?",
  "Have you ever been caught cheating on a test?",
  "What's the most embarrassing thing your parents have caught you doing?",
  "Have you ever blamed someone else for something you did?",
  "What's the weirdest thing you've collected?",
  "Have you ever kissed someone you shouldn't have?",
  "What's the most awkward family moment you've experienced?",
  "Have you ever lied to get out of a speeding ticket?",
  "What's a food you secretly love but are embarrassed to admit?",
  "Have you ever pretended to understand something you didn’t?",
  "What's the worst date you've ever been on?",
  "Have you ever laughed at a joke you didn't understand?",
  "What's a ridiculous thing you're genuinely afraid of?",
  "Have you ever cheated in a video game?",
  "What's one thing you wish you could do over?"
];

app.get('/', (req, res) => {
  const randomIndex = Math.floor(Math.random() * truthQuestions.length);
  const question = truthQuestions[randomIndex];
  res.json({ truthQuestion: question });
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Truth service is running on port ${PORT}`);
});

  
